# ---------------------------------------------------------
# type "make" command in Unix to create report.pdf 
# ---------------------------------------------------------

all: AnaliseTeorica.m
	octave $< > $@

clean:
	@rm -rf *.tex
	
.PHONY: clean


